name: Flutter for Android

on:
  push: 
    branches: ["**"]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: document_ocr/
    steps:
      - uses: actions/checkout

      - name: Set up JDK 1.8
        uses: actions/setup-java
        with:
          java-version: '17'
          distribution: corretto

      - name: Setup Android SDK
        uses: android-actions/setup-android

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter
        with:
          channel: stable
          version: 3.0.2

      - name: Install dependencies
        run: flutter pub get

      - name: Run widget tests
        run: flutter test . 